### ISSUE TITLE
sample.R

### ISSUE THREAD

**Issue by chrishwiggins** [winstonll/SynC#2]
https://github.com/winstonll/SynC/blob/ce7bfa601f731a0feb66234c7a6968c094fc7cb3/models/synthetic_population.R#L4

hello!

did you mean to push a "sample.R" to the repo?

sorry to be dense but when I run this i get 

====
prompt: /usr/local/bin/R -f models/synthetic_population.R 

R version 4.0.3 Patched (2020-10-13 r79346) -- "Bunny-Wunnies Freak Out"
Copyright (C) 2020 The R Foundation for Statistical Computing
Platform: x86_64-apple-darwin17.0 (64-bit)

R is free software and comes with ABSOLUTELY NO WARRANTY.
You are welcome to redistribute it under certain conditions.
Type 'license()' or 'licence()' for distribution details.

  Natural language support but running in an English locale

R is a collaborative project with many contributors.
Type 'contributors()' for more information and
'citation()' on how to cite R or R packages in publications.

Type 'demo()' for some demos, 'help()' for on-line help, or
'help.start()' for an HTML browser interface to help.
Type 'q()' to quit R.

> library(readr)
> file_dir = ''
> data_dir = ''
> source(paste(file_dir, 'sample.R', sep = ''))
Error in file(filename, "r", encoding = encoding) : 
  cannot open the connection
Calls: source -> file
In addition: Warning message:
In file(filename, "r", encoding = encoding) :
  cannot open file 'sample.R': No such file or directory
Execution halted
prompt:
====

**Comment by winstonll** [comment]
Hi Chris,
Thanks for pointing this out. It's a little typo in the source code where we should instead be calling `functions.R`. I'm made the change so hopefully it works this time.
Thanks!
